receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  debug:
    verbosity: detailed

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]
